### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Seb-AS** [matrix3d/spriteflexjs#1]
Hi, great framework, but I wasn't able to  compile using FlexJS using terminal in mac
or  using FDT because is always pointing to the playerglobal.swc  instead of using the flash folder you provided.

Thanks

Feb 15, 2016 3:23:40 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /Documents/spriteflexjs/test/bin/js-debug/com/hsharma/hungryHero/screens/InGame.js:28: ERROR - required "flash.utils.getTimer" namespace never provided
goog.require('flash.utils.getTimer');
^

Feb 15, 2016 3:23:40 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /Documents/spriteflexjs/test/bin/js-debug/com/hsharma/hungryHero/screens/Welcome.js:13: ERROR - required "flash.net.navigateToURL" namespace never provided
goog.require('flash.net.navigateToURL');
^

Feb 15, 2016 3:23:40 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /Documents/spriteflexjs/test/bin/js-debug/flash/display/DisplayObject.js:17: ERROR - required "flash.utils.getTimer" namespace never provided
goog.require('flash.utils.getTimer');
^

Feb 15, 2016 3:23:40 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /Documents/spriteflexjs/test/bin/js-debug/flash/display/Stage.js:16: ERROR - required "flash.utils.getTimer" namespace never provided
goog.require('flash.utils.getTimer');

**Comment by matrix3d** [comment]
the lib need the flexjs 0.6.
which version flexjs skd  you are useing?

**Comment by matrix3d** [comment]
and pls ant the build.xml

**Comment by Seb-AS** [comment]
I'm using 0.5, Tried to build 0.6 but a lot of errors, I'll wait until the release of 0.6, thanks

**Comment by matrix3d** [comment]
no need build,just down it,right click ,show dev build
![Uploading 无标题.jpg…]()

**Comment by matrix3d** [comment]
![1](https://cloud.githubusercontent.com/assets/4150631/13095178/bb7119e4-d54a-11e5-89f7-9477e4efc509.jpg)
no need build,just down it,right click ,show dev build

**Comment by Seb-AS** [comment]
Thanks, I didn't know you can switch to nightly builds.

SpriteflexJs works perfectly now, thanks again
