### ISSUE TITLE
required version

### ISSUE THREAD

**Issue by ghost** [matrix3d/spriteflexjs#10]
Hi lizhi, i try to transpile samples provided, but it no longer works, every sample ends with error :

C:\Users\spanvega\Desktop\matrix3d-spriteflexjs-369e8d1\src\flash\utils\getTimer.as:5
Call to a possibly undefined method now through a reference with static type Date.
		return Date.now() - SpriteFlexjs.startTime;

I use flexjs 0.7 from latest Apache flex sdk

**Comment by matrix3d** [comment]
download the flexjs 0.8.
or remove the code line date,now();

**Comment by spanvega** [comment]
u have a download link for 0.8 since it's still in beta ?

**Comment by matrix3d** [comment]
,right click ,show dev build

**Comment by matrix3d** [comment]
https://github.com/matrix3d/spriteflexjs/issues/1

**Comment by spanvega** [comment]
thanks, compilation works with 0.8 but i got an error at launch in browser

`<img src="http://img15.hostingpics.net/pics/395819launchbug.png"/>`

btw can you give some details about values that can be used in CONFIG::js_only {}

**Comment by matrix3d** [comment]
this is the webserver of flashdevelop bug.
you can use other webserver(iis,tomcat) etc.
