### ISSUE TITLE
Update WebGL texture

### ISSUE THREAD

**Issue by Diamanter** [matrix3d/spriteflexjs#13]
Another stupid question.
I need to use  bitmapdata.draw(); This works fine before first use of this bitmapdata, BUT all runtime changes ignored in WebGL mode. 

Is there a way to reupload bitmapdata pixels during runtime?

My test snippet, just added in TestBitmapDraw:
	stage.addEventListener(MouseEvent.CLICK, function():void{bmd.fillRect(bmd.rect, 0xFFFF0000);});

**Comment by matrix3d** [comment]
mark

**Comment by Diamanter** [comment]
hm, mark? )

**Comment by matrix3d** [comment]
i have find the bug code.the blendmode use the last blendmode.
and i now have no time to fixed it.

**Comment by matrix3d** [comment]
yes mark it.and no time to fix it.
