### ISSUE TITLE
Problem when using SpriteFlexJS with FlexJS SDK v0.8 "NullPointerExecption"

### ISSUE THREAD

**Issue by blackjyn** [matrix3d/spriteflexjs#15]
When using SpriteFlexJS with FlexJS v0.7 I have NO problem et all , and can transpile successfully without any problem

However when using FlexJS v0.8 I got this:
![spriteflexjs null pointer exeption w flexjs 0 8](https://user-images.githubusercontent.com/6046191/28654984-a9d676f4-72c2-11e7-85be-e4950a5e1f57.png)

Is this SpriteFlexJS problem OR FlexJS SDK problem? 
Thank you

**Comment by matrix3d** [comment]
I haven't tested flexjs 0.8. It seems that this method of deleting loop dependent arguments is different from the 0.7.

**Comment by blackjyn** [comment]
Thank you 
I'll be waiting for the update 👍

**Comment by matrix3d** [comment]
i do not know,but ths args diff with 0.7.
-remove-circulars
and pls look at the flexjs0.8 doc.

**Comment by blackjyn** [comment]
Unfortunately, the Falcon compiler reference on Flex's chwiki was last updated  on September 2016

:(

**Comment by matrix3d** [comment]
pls push a bug at.http://apache-flex-development.2333347.n4.nabble.com/

**Comment by blackjyn** [comment]
AH,.. Finally it caught up! :D  
To use SpriteFlexJS with FlexJS v0.8 , new param must be explicitly declared : **-targets="JSFlex"** 

This is the .bat file that I modified and works with FlexJS v0.8
```
set FLEX_HOME=d:/sdk/flexjs.0.8
set LIB=d:/sdk/Spriteflexjslib
set main=src/TestXML.as
start %FLEX_HOME%/js/bin/mxmlc -targets="JSFlex" -external-library-path="%FLEX_HOME%\js\libs\js.swc" -compiler.source-path=%LIB% %main%

```

They have refine asjsc and mxmlc
asjsc by default will NOT include HTML template unless you define and link it
mxmlc by default will compile to HTML and SWF

-targets param has two values: JSFlex and SWF 

by running the .bat file above, the transpiation gets done correctly just I did with FlexJS v0.7
:)

**Comment by matrix3d** [comment]
nice job
