### ISSUE TITLE
Works with Apache Royale 

### ISSUE THREAD

**Issue by blackjyn** [matrix3d/spriteflexjs#20]
I can confirm that this is works with Apache Royale v0.9.1 too 😄

**Comment by matrix3d** [comment]
yes ,it is work with royale.
but,just some char encoding bug.

**Comment by blackjyn** [comment]
are you going to change the name?
since FlexJS is gone now?

**Comment by matrix3d** [comment]
I still do not want to change the name, first of all, I think flexjs is a good name, followed by this project is not very popular, very few people know this project, so I do not want to change the name

**Comment by kennylerma** [comment]
Currently, I don't think the name matters.  I think this project has a lot potential, but was largely incomplete which may have led to an initial lack of interest.  I'm hoping to create a more complete representation of the Flash API  for Canvas to help gain traction and then move on to WebGL.  Perhaps, when more is complete, a more descriptive name might make sense down the road.

**Comment by carlosrovira** [comment]
Hi,

IMHO, this project would be a great addition to Apache Royale project and will help both projects grow and be of more interest for people that comes from Flash/Flex ecosystem. Hope you could consider donate to ASF to join us and continue the work from Apache Royale.

**Comment by matrix3d** [comment]
Flexjs is a beta version. Then keep updating, every time the update, the spriteflexjs library will not work, compile errors. Previously, every time I made a mistake, I went to ask questions, then got a solution, or they changed the compiler. This is always very tired. Unfortunately, I don't have time to change the compiler.

**Comment by matrix3d** [comment]
The latest version of flexjs is now incompatible with spriteflexjs.

**Comment by carlosrovira** [comment]
Hi, I'd like to see this project officially part of #ApacheRoyale too, but I don't have the time right now. I'm completely committed to complete #Jewel UI Set. Others that would make this happen can make the effort. In theory is just a matter of making it build with maven. Having it integrated with maven build will make it more easy to make changes in the compiler and see all continues working.

**Comment by carlosrovira** [comment]
As a note, we should always talk about #ApacheRoyale a not #FlexJS. FlexJS no longer exists, and all that work is now part of Apache Royale

**Comment by carlosrovira** [comment]
Hi @kennylerma that would be awesome. Hope you can work with @matrix3d to make this happen. I think once it's hosted as part of #ApacheRoyale that will be better for all since will be more people that can contribute to it. Thanks! :)
