### ISSUE TITLE
Compatibility with Royale 0.9.4

### ISSUE THREAD

**Issue by feathersuser** [matrix3d/spriteflexjs#21]
Hi, i'm using Royale 0.9.4, i made a simple test.bat following the example, and it don't work, are there limitation with the Royale version ?

set FLEX_HOME=C:\SDK\Royale\royale-asjs
set main=TestBitmapDataSand

set ARGS=-remove-circulars
start %FLEX_HOME%/js/bin/mxmlc %ARGS% -external-library-path="%FLEX_HOME%\js\libs\js.swc" -compiler.source-path=../src src/%main%.as -define=CONFIG::as_only,false -define=CONFIG::js_only,true

Using Royale Compiler codebase: C:\SDK\Royale\royale-asjs\js\bin\..\..
Using Royale SDK: C:\SDK\Royale\royale-asjs\js\bin\..\..
MXMLJSC
-sdk-js-lib=C:\SDK\Royale\royale-asjs\js\bin\..\..\frameworks\js\Royale\generated-sources
-remove-circulars
-external-library-path=C:\SDK\Royale\royale-asjs\js\libs\js.swc
-compiler.source-path=../src
src/TestBitmapDataSand.as
-define=CONFIG::as_only,false
-define=CONFIG::js_only,true
Chargement de la configuration : C:\SDK\Royale\royale-asjs\frameworks\royale-config.xml

scanning for overrides: IEventDispatcher
scanning for overrides: EventDispatcher
scanning for overrides: IBitmapDrawable
scanning for overrides: DisplayObject
scanning for overrides: InteractiveObject
scanning for overrides: DisplayObjectContainer
scanning for overrides: Sprite
scanning for overrides: TestBitmapDataSand
scanning for overrides: P
scanning for overrides: BitmapFilter
scanning for overrides: DropShadowFilter
scanning for overrides: BitmapData
scanning for overrides: Bitmap
scanning for overrides: LoaderInfo
scanning for overrides: Point
scanning for overrides: Stage
scanning for overrides: Graphics
scanning for overrides: Matrix
scanning for overrides: BlendMode
scanning for overrides: GlowFilter
scanning for overrides: Transform
scanning for overrides: SpriteFlexjs
scanning for overrides: Rectangle
scanning for overrides: Vector3D
scanning for overrides: Event
scanning for overrides: MouseEvent
scanning for overrides: IGraphicsFill
scanning for overrides: IGraphicsPath
scanning for overrides: URLVariables
scanning for overrides: StageAlign
scanning for overrides: Stage3D
scanning for overrides: IGraphicsData
scanning for overrides: GraphicsSolidFill
scanning for overrides: GraphicsGradientFill
scanning for overrides: IRenderer
scanning for overrides: GraphicsEndFill
scanning for overrides: ColorTransform
scanning for overrides: NativeMenu
scanning for overrides: ContextMenu
scanning for overrides: TextSnapshot
scanning for overrides: KeyboardEvent
scanning for overrides: IDataInput
scanning for overrides: IDataInput2
scanning for overrides: IDataOutput
scanning for overrides: IDataOutput2
scanning for overrides: ByteArray
scanning for overrides: GraphicsBitmapFill
scanning for overrides: BitmapDataChannel
scanning for overrides: Loader
scanning for overrides: Matrix3D
scanning for overrides: BaseRenderer
scanning for overrides: AccessibilityImplementation
scanning for overrides: GLCanvasRenderingContext2D
scanning for overrides: StageScaleMode
scanning for overrides: GraphicsPath
scanning for overrides: StageQuality
scanning for overrides: GraphicsTrianglePath
scanning for overrides: AccessibilityProperties
scanning for overrides: TouchEvent
scanning for overrides: PerspectiveProjection
scanning for overrides: WebGLRenderer
scanning for overrides: IGraphicsStroke
scanning for overrides: BitmapTexture
scanning for overrides: GraphicsStroke
scanning for overrides: GLGraphicsPath
scanning for overrides: Context3DTextureFormat
scanning for overrides: TextureBase
scanning for overrides: Texture
scanning for overrides: ContextMenuClipboardItems
scanning for overrides: GLVertexBufferSet
scanning for overrides: TextFormat
scanning for overrides: Context3DVertexBufferFormat
scanning for overrides: GLIndexBufferSet
scanning for overrides: Context3DProgramType
scanning for overrides: Context3DBlendFactor
scanning for overrides: Endian
scanning for overrides: Context3DTriangleFace
scanning for overrides: GLCanvasPattern
scanning for overrides: URLRequest
scanning for overrides: Orientation3D
scanning for overrides: Context3D
scanning for overrides: GLDrawable
scanning for overrides: GLPath2D
scanning for overrides: Program3D
scanning for overrides: GraphicsPathCommand
scanning for overrides: GradientType
scanning for overrides: LoaderContext
scanning for overrides: ContextMenuBuiltInItems
scanning for overrides: Context3DCompareMode
scanning for overrides: IndexBuffer3D
scanning for overrides: MemArray
scanning for overrides: VideoTexture
scanning for overrides: RectangleTexture
scanning for overrides: VertexBuffer3D
scanning for overrides: CubeTexture
C:\Users\user\Desktop\spriteflexjs-master\src\flash\display\Stage.as(281): col: 3 Erreurá: A conflict exists with inherited definition __update in class flash.display.DisplayObjectContainer.

                private function __update():void {
                ^

C:\Users\user\Desktop\spriteflexjs-master\src\flash\display\Stage.as(410): col: 3 Erreurá: A conflict exists with inherited definition constructor in class Object.

                public function get constructor ():* { return _constructor; }
                ^

C:\Users\user\Desktop\spriteflexjs-master\src\flash\display\Stage.as(411): col: 3 Erreurá: A conflict exists with inherited definition constructor in class Object.

                public function set constructor (c:*):void { _constructor = c; }
                ^

C:\Users\user\Desktop\spriteflexjs-master\src\flash\display\Stage.as(1023): col: 3 Erreurá: A conflict exists with inherited definition transform in class flash.display.DisplayObject.

                public function set transform (value:Transform):void { _transform = value; }
                ^

C:\Users\user\Desktop\spriteflexjs-master\src\flash\display\Stage.as(281): col: 3 Erreurá: A conflict exists with inherited definition __update in class flash.display.DisplayObjectContainer.

                private function __update():void {
                ^

C:\Users\user\Desktop\spriteflexjs-master\src\flash\display\Stage.as(410): col: 3 Erreurá: A conflict exists with inherited definition constructor in class Object.

                public function get constructor ():* { return _constructor; }
                ^

C:\Users\user\Desktop\spriteflexjs-master\src\flash\display\Stage.as(411): col: 3 Erreurá: A conflict exists with inherited definition constructor in class Object.

                public function set constructor (c:*):void { _constructor = c; }
                ^

C:\Users\user\Desktop\spriteflexjs-master\src\flash\display\Stage.as(1023): col: 3 Erreurá: A conflict exists with inherited definition transform in class flash.display.DisplayObject.

                public function set transform (value:Transform):void { _transform = value; }
                ^

10.3083943 seconds

**Comment by matrix3d** [comment]
https://github.com/apache/royale-asjs/issues/260
Since the royale changes are frequent, each compilation will add or remove some compilation options, so I have not tested it with the latest royale version. But you can use flexjs sdk, this sdk is more stable.
If you want to compile with royale, you need to contact the developer of royale.

**Comment by Harbs** [comment]
These are legitimate errors. The Royale compiler has improved a lot over the older FlexJS compiler and it catches more errors than the older compiler caught.

I've fixed the code in #22 so it compiles with the latest build of Royale. I'd strongly recommend that you use that instead.

**Comment by matrix3d** [comment]
I also hope to switch to the latest compiler. I have tried it, but gave up. I don't have much time to study the compiler source. If I research the compiler source and modify the compiler source. spriteflexjs hopefully compile with the latest compiler.

**Comment by Harbs** [comment]
You don't need to modify anything. Just download the latest build of Royale and point to that.

FYI, I wouldn't use the latest nightly until this bug is resolved: https://github.com/apache/royale-compiler/issues/74

**Comment by Harbs** [comment]
Also: I haven't tested your batch script, but the shell script works with the example I tried.

**Comment by kennylerma** [comment]
Hey guys, I had already done the corrections @Harbs just added.  I've made a lot of updates and changes that I need to get out to this repo.  It's a large restructure, so I've postponed a bit and been really busy in my daily life.  Additionally, I have a build of FlashDevelop that works for creating AS3 only builds using Royale.  I'll have to add support for MXML later, but Spriteflexjs works great with Royale.

@feathersuser since Spriteflexjs is a pure AS3 library, you should use asjsc to compile instead of mxmlc since you are not using MXML files.

I'll work on getting my code out this weekend.

**Comment by Harbs** [comment]
@kennylerma That's great to hear!

**Comment by carlosrovira** [comment]
Really cool @kennylerma , I'll want to find time as you get to that point to try to use Royale and spriteflexjs together and see the results. So any example project or something similar would be very appreciated to give it a try. Thanks! :)

**Comment by matrix3d** [comment]
@carlosrovira i just find the 0.9.4,where is the 0.9.6,thanks

**Comment by matrix3d** [comment]
@carlosrovira some bug of 0.9.7

```
F:\proj\spriteflexjs\examples>D:\sdk\apache-royale-0.9.7-bin-js\royale-asjs/js/bin/asjsc.bat src\TestBedMain.as -js-output-optimization=skipAsCoercions  -library-path+=D:\sdk\apache-royale-0.9.6-bin-js\royale-asjs\js\libs\js.swc  -external-library-path+=lib\pixijs.swc  -source-path+=..\src -source-path+=src -source-path+=D:\sdk\apache-royale-0.9.6-bin-js\royale-asjs\js\libs -warn-public-vars=false -remove-circulars=true -js-compiler-option+="--compilation_level SIMPLE_OPTIMIZATIONS" -targets=JSRoyale -define=CONFIG::as_only,false -define=CONFIG::js_only,true -warnings=false 
MXMLJSC
-js-output-type=jsc
+configname=js
src\TestBedMain.as
-js-output-optimization=skipAsCoercions
-library-path+=D:\sdk\apache-royale-0.9.6-bin-js\royale-asjs\js\libs\js.swc
-external-library-path+=lib\pixijs.swc
-source-path+=..\src
-source-path+=src
-source-path+=D:\sdk\apache-royale-0.9.6-bin-js\royale-asjs\js\libs
-warn-public-vars=false
-remove-circulars=true
-js-compiler-option+=--compilation_level SIMPLE_OPTIMIZATIONS
-targets=JSRoyale
-define=CONFIG::as_only,false
-define=CONFIG::js_only,true
-warnings=false
五月 15, 2020 4:49:33 下午 com.google.javascript.jscomp.LoggerErrorManager println
严重: ERROR - Duplicate extern input: externs/svg.js
```

2,
the spriteflexjs.as
```
/**
 * @export
 * @nocollapse
 * @type {Function}
 */
SpriteFlexjs.requestAnimationFrame = /* implicit cast */ org.apache.royale.utils.Language.as(window["requestAnimationFrame"] || window["webkitRequestAnimationFrame"] || window["mozRequestAnimationFrame"] || window["oRequestAnimationFrame"] || window["msRequestAnimationFrame"] || function(callback) {
  window["setTimeout"](callback, 1000 / 60);
}, Function, true);
```

```
SpriteFlexjs.js:141 Uncaught ReferenceError: org is not defined
    at SpriteFlexjs.js:141
```

**Comment by carlosrovira** [comment]
Hi Lizhi,
please report this on mailing list. It could be related to some changes @joshtynjala did, and you probably need to update SpriteJS to support it. But can't ensure. 
Thanks

**Comment by matrix3d** [comment]
@joshtynjala pls

**Comment by matrix3d** [comment]
Is there a compiled function that ignores as globally
Then use spriteflexjs.as to org.as function. But can't find the function org.as

**Comment by matrix3d** [comment]
And the generated JS size seems a bit large. The original version was 97k, now 900k

**Comment by joshtynjala** [comment]
This issue does not appear to be related to any of my changes to the compiler. However, it is definitely a compiler issue.

Based on my initial investigation, the dependencies are not being added in the correct order in the goog.addDependency() calls that we generate in js-debug/index.html. It appears that Language.js is being loaded after Spriteflexjs.js, but Language.js should be loaded first.

**Comment by carlosrovira** [comment]
My thinking is that this project is very isolated and with almost no communication with Apache Royale, that makes it very difficult to support it. In the other hand, in my case, without a proper maven support, for me is very difficult to even try it.

**Comment by joshtynjala** [comment]
>  TestBedMain.js:717 Uncaught TypeError: Cannot read property 'apache' of undefined

apache/royale-compiler@6557ac8878a78c04d883f89e4560adef5d5eff25 should fix this issue.

**Comment by carlosrovira** [comment]
Thanks Josh for taking the time to look at it

**Comment by matrix3d** [comment]
@carlosrovira 
Why can't mvn compile? The project structure is very simple. Only used the function of compiling js. Then 2 source code directories, one is src of flash api, and the other is src of example

**Comment by matrix3d** [comment]
@carlosrovira @joshtynjala @Harbs 
pls look at the size of js .706k!
https://gist.github.com/matrix3d/007b7594a479e1713643699deec4d7ec

the old one 90k
https://github.com/matrix3d/matrix3d.github.io/blob/master/assets/html5/flexjsstage3d/bin/js-release/PuyoDot3JS.js


Why is the new sdk 10 times larger than the old sdk? Are there any new compilation options that can reduce this size?

**Comment by matrix3d** [comment]
@joshtynjala @carlosrovira @Harbs 
the bug of --compilation_level ADVANCED_OPTIMIZATIONS of TestBedMain.as
```

  | tf | @ | TestBedMain.js:417
-- | -- | -- | --
  | ai | @ | TestBedMain.js:646
  | A.ComputeTOI | @ | TestBedMain.js:319
  | N.SolveTOI | @ | TestBedMain.js:188
  | N.Step | @ | TestBedMain.js:172
  | M.Update | @ | TestBedMain.js:141
  | Cl.update | @ | TestBedMain.js:1021
  | lf | @ | TestBedMain.js:24
  | kf.dispatchEvent | @ | TestBedMain.js:24
  | P.dispatchEvent | @ | TestBedMain.js:213
  | T.Rh | @ | TestBedMain.js:353
  | requestAnimationFrame (async) |   |  
  | T.Rh | @ | TestBedMain.js:353
  | requestAnimationFrame (async) |   |  
  | T.Rh | @ | TestBedMain.js:353
  | requestAnimationFrame (async) |   |  
  | T.Rh | @ | TestBedMain.js:353
  | requestAnimationFrame (async) |   |  
  | T.Rh | @ | TestBedMain.js:353
  | requestAnimationFrame (async) |   |  
  | T.Rh | @ | TestBedMain.js:353
  | requestAnimationFrame (async) |   |  
  | T.Rh | @ | TestBedMain.js:353
  | requestAnimationFrame (async) |   |  
  | T.Rh | @ | TestBedMain.js:353
  | requestAnimationFrame (async) |   |  
  | T.Rh | @ | TestBedMain.js:353
  | setTimeout (async) |   |  
  | T | @ | TestBedMain.js:349
  | get | @ | TestBedMain.js:377
  | rk | @ | TestBedMain.js:763
  | Cl | @ | TestBedMain.js:1016
  | (anonymous) | @ | index.html:13


```

**Comment by matrix3d** [comment]
this line set A.h.sweepA    A.h.sweepB
```
A.prototype.ComputeTOI = function(a, b) {
    A.h.proxyA.Set(this.m_fixtureA.GetShape());
    A.h.proxyB.Set(this.m_fixtureB.GetShape());
    A.h.sweepA = a;
    A.h.sweepB = b;
    A.h.tolerance = B.b2_linearSlop;
    return ai(A.h)
}
```

but in the function of ai,d.sweepA ==null;
```
function ai(a) {
    ++Wj;
    var b = a.proxyA
      , c = a.proxyB
      , d = a.sweepA
      , f = a.sweepB;
    tf(d.t0 == f.t0);
```

**Comment by matrix3d** [comment]
the getter of h,get new $h?
```
Object.defineProperties(A, {
    h: {
        get: function() {
            var a = new $h;
            Object.defineProperty(A, 's_input', {
                value: a,
                writable: !0
            });
            return a
        },
        set: function(a) {
            Object.defineProperty(A, 's_input', {
                value: a,
                writable: !0
            })
        },
        configurable: !0
    }
});
```

**Comment by matrix3d** [comment]
the SIMPLE_OPTIMIZATIONS set sweepA,just set the obj.not into the defineproperties.
it is good.

```
Box2D.Dynamics.Contacts.b2Contact.prototype.ComputeTOI = function(a, b) {
    Box2D.Dynamics.Contacts.b2Contact.s_input.proxyA.Set(this.m_fixtureA.GetShape());
    Box2D.Dynamics.Contacts.b2Contact.s_input.proxyB.Set(this.m_fixtureB.GetShape());
    Box2D.Dynamics.Contacts.b2Contact.s_input.sweepA = a;
    Box2D.Dynamics.Contacts.b2Contact.s_input.sweepB = b;
    Box2D.Dynamics.Contacts.b2Contact.s_input.tolerance = Box2D.Common.b2Settings.b2_linearSlop;
    return Box2D.Collision.b2TimeOfImpact.TimeOfImpact(Box2D.Dynamics.Contacts.b2Contact.s_input)
}
```

**Comment by kennylerma** [comment]
This is likely this issue of Closure re-naming public variables when using ADVANCED_OPTIMIZATIONS.
I haven't ever been able to use that level of compression because of it. @joshtynjala is working on this re-naming issue.  I need to test the nightly builds and see where we are at.

**Comment by matrix3d** [comment]
0.9.8 get

**Comment by matrix3d** [comment]
@joshtynjala 
assertType.js:26 Uncaught TypeError: org.apache.royale.debugging.assert is not a function
    at Object.org.apache.royale.debugging.assertType (assertType.js:26)
    at XML.addChildInternal (XML.js:870)
    at Function.XML.insertAttribute (XML.js:423)
    at Function.XML.iterateElement (XML.js:456)
    at Function.XML.fromNode (XML.js:493)
    at Function.XML.iterateElement (XML.js:471)
    at XML.XML_parseXMLStr (XML.js:738)
    at new XML (XML.js:29)
    at ButtonTestUI.js:54

**Comment by Harbs** [comment]
Have you included `CoreJS.swc`?

**Comment by matrix3d** [comment]
yes have

**Comment by matrix3d** [comment]
If you do not add core, it will compile errors, this should be a circular dependency bug

**Comment by Harbs** [comment]
Hmm. Does `remove-circulars` make the error go away?

**Comment by joshtynjala** [comment]
Using the latest compiler commits, TestBedMain and TestBox2D both appear to be working correctly with ADVANCED_OPTIMIZATIONS.

**Comment by matrix3d** [comment]
nice job,it is work.1m->500k ,the js file size
