### ISSUE TITLE
JS problem

### ISSUE THREAD

**Issue by Diamanter** [matrix3d/spriteflexjs#3]
Hello, I'm trying to compile starling example https://github.com/matrix3d/Starling-Framework with https://github.com/matrix3d/spriteflexjs and FlexJS6.

Compilation is OK with your "build.bat" (if to add "BitmapData implements IBitmapDrawable") but  I've got 3 errors on running:

Uncaught SyntaxError: Unexpected token ILLEGAL
Uncaught ReferenceError: org is not defined
Uncaught ArgumentError

I can fix 1 and 3 with a simple change, but I have no idea how to fix:

Stage.js: flash.display.Stage.prototype.__update = function() {
  this.requestAnimationFrameHander = requestAnimationFrame(org.apache.flex.utils.Language.closure(this.__update, this, '__update'));

<-- ReferenceError: org is not defined

Maybe it lost some goog.require or goog.inherits? I'm not so good in Javascript, I know Actionscript.

Can you help, please? )

Denis.

**Comment by matrix3d** [comment]
now hard make starling run with flexjs.the flexjs sdk ,goog.require bug.

http://apache-flex-development.2333347.n4.nabble.com/Starling-framework-compiled-to-JavaScript-td52188.html
