### ISSUE TITLE
Problem with Loader

### ISSUE THREAD

**Issue by pilipenko9** [matrix3d/spriteflexjs#4]
Hello, when assembling any of your example, where external resources loading, can't get loader working

the project is going, but the resources just are not loaded, there is no such event as the end / error etc
added 
imageloader.contentLoaderInfo.addEventListener(HTTPStatusEvent.HTTP_STATUS, httpStatusHandler);
imageloader.contentLoaderInfo.addEventListener(Event.INIT, initHandler);
imageloader.contentLoaderInfo.addEventListener(IOErrorEvent.IO_ERROR, ioErrorHandler);
imageloader.contentLoaderInfo.addEventListener(Event.OPEN, openHandler);
imageloader.contentLoaderInfo.addEventListener("progress", progressHandler);
imageloader.contentLoaderInfo.addEventListener(Event.UNLOAD, unLoadHandler);

in bat pointed to last flexjs 
set FLEX_HOME=D:/apache-flex-flexjs-0.6.0-bin

maybe u know what the problem? thank you
for example TestBitmapDataSand working well

and i notices that i dont have class Image which u r using in Loader(ide didnt see it at least)

**Comment by matrix3d** [comment]
thanks open issues.but it is this example work?this example base on loader.
and it now just support the complete event.
https://github.com/matrix3d/spriteflexjs/blob/master/src/flash/display/Loader.as#L38

i have not add all the event now

**Comment by matrix3d** [comment]
and what ide u useing?i use the fd.and the image in the js.swc.
https://github.com/matrix3d/spriteflexjs/blob/master/test/build.bat#L11

**Comment by pilipenko9** [comment]
intellij idea, but i just editing code there. building with ur bat file. could u pls post ur js.swc? thats strange

**Comment by pilipenko9** [comment]
and ur flex_home is flexjs7, is it 0.7 version? I got 0.6

**Comment by matrix3d** [comment]
https://github.com/matrix3d/spriteflexjs/issues/1
get the 0.7

**Comment by pilipenko9** [comment]
well  I tried to install 0.7 but the installation was stopped on unit tests flex-flexunit\FlexUnit4AntTasks\build.xml : 55  Error running javax.exe compiler. and so after building sdk i got error too flex-asjs\frameworks\projects\Core\src\test\flex\build.xml 117   mxmlc task failed
and now i dont see Image in flex-asjs\js\libs\js.swc (

**Comment by matrix3d** [comment]
pls try this
https://www.dropbox.com/s/13mrzk4asw1qcq2/flexjs7.zip?dl=0

**Comment by pilipenko9** [comment]
here is my bat 
set FLEX_HOME=D:/flexjs7
::set main=TestBitmapDraw
::set main=TestHungryHero
::set main=TestByteArrayVSArray
::set main=Main
set main=TestHungryHero

set ARGS=-remove-circulars
::set ARGS=-debug=true -remove-circulars
::set ARGS=-remove-circulars -js-compiler-option="--compilation_level WHITESPACE_ONLY"
start %FLEX_HOME%/js/bin/mxmlc %ARGS% -external-library-path="%FLEX_HOME%\js\libs\js.swc" -compiler.source-path=../src src/%main%.as -define=CONFIG::as_only,false -define=CONFIG::js_only,true

when i launch index.html i got stucked on this http://c2n.me/3zb2wQI , Do I need to do anything other than run bat file? here is end of console http://c2n.me/3zb3hGQ

**Comment by matrix3d** [comment]
you need a webserver.iis etc

**Comment by pilipenko9** [comment]
when I try to download a remote resource http://c2n.me/3zbO9rP it didnt load too

**Comment by matrix3d** [comment]
the index must in webserver

**Comment by pilipenko9** [comment]
that doesnt help http://c2n.me/3ze1fep

**Comment by matrix3d** [comment]
is it working good?
http://matrix3d.github.io/assets/html5/flexjsstage3d/bin/js-release/#test_hugryhero
pls paste the output console.log

**Comment by pilipenko9** [comment]
yes. it working well. Browser console is empty

**Comment by matrix3d** [comment]
it working well,but your js,not work.
so pls get your loader test js,and as code.
i will debug it.

**Comment by pilipenko9** [comment]
[test.zip](https://github.com/matrix3d/spriteflexjs/files/317839/test.zip)

**Comment by matrix3d** [comment]
BitmapData.js:122 Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

you can not load http://cs416419.vk.me/v416419800/81a5/QxO0EJO_ORk.jpg
try QxO0EJO_ORk.jpg(it is work)

**Comment by matrix3d** [comment]
![default](https://cloud.githubusercontent.com/assets/4150631/16115356/0cfce088-33f9-11e6-8cfb-069371326d42.gif)
you can debug it yourself

**Comment by pilipenko9** [comment]
great. When i placed both index and resources in webserver it sratrs working) hungryhero
Thank you very much!
and one more question. why there is no method loadbytes in Loader?

**Comment by matrix3d** [comment]
the loadbytes will coming soon.but i have not time now.

**Comment by pilipenko9** [comment]
I forgot to ask, did u try to load swf into asjs?

**Comment by matrix3d** [comment]
swf hard to load,it is need big lib as3swf,and lzma lib.zip lib.
so not easy load it.
but maybe have a tool swf2something.exe.
and load the something(custom format of swf)
