### ISSUE TITLE
How to compile with FlexJS7?

### ISSUE THREAD

**Issue by Diamanter** [matrix3d/spriteflexjs#5]
I tried with the last sdk 7 version, but I got a few compilation errors:

Date.now(); <-- now() is not defined, I replaced with (new Date()).getTimer()
and
gl.uniform4fv(getUniformLocation(name), data); <--wrong data variable type. I replaced with:
gl.uniform4fv(getUniformLocation(name), Object(data));

But on runtime all test projects fail with "this.path is not defined".

How to get the correct SDK?

It was all OK a month ago with SDK 6.

**Comment by matrix3d** [comment]
pls push bug at apache-flex-development.2333347.n4.nabble.com.
may be the remove the data.new

**Comment by matrix3d** [comment]
it is work with flexjs7 https://github.com/matrix3d/spriteflexjs/issues/1

**Comment by matrix3d** [comment]
![spriteflexjs_flashdevelop](https://cloud.githubusercontent.com/assets/4150631/22914979/fe1f5b2a-f2ae-11e6-8cbf-e0f383f87b82.gif)

**Comment by matrix3d** [comment]
0.9.8 get
