### ISSUE TITLE
Problem with scaled beginBitmapFill

### ISSUE THREAD

**Issue by Diamanter** [matrix3d/spriteflexjs#7]
I found that several beginBitmapFill with scaled matrix work wrong.

```
for (var i:int=0; i<numChars; ++i) {
    target.beginBitmapFill(bmd, new Matrix(0.5,0,0,0.5,0,0), true, true);
    target.drawRect(i*50, 0, 50, 50);
}
```

Only first bitmap fill works correctly. After that ctx.matr has wrong values.
I have no idea how to fix it in gldraw() without context.save() function.

**Comment by matrix3d** [comment]
我之前实现了，context.save.但是后来我给删除了，为了更好的性能。而且我认为这个功能不是很重要

**Comment by Diamanter** [comment]
Я понял. Пока сделал такой трюк:
https://github.com/Diamanter/spriteflexjs/commit/3523bd8c9f315b4426fbdbee3c6353dc29841790

Теперь BitmapFont в моём проекте наконец заработал.

**Comment by matrix3d** [comment]
this is a bug,i will try fix it ,one or two days
