### ISSUE TITLE
类型转换error

### ISSUE THREAD

**Issue by elseswitch** [matrix3d/spriteflexjs#9]
![1](https://cloud.githubusercontent.com/assets/2967770/18771772/18a22394-8174-11e6-82b2-2841ac8a4b98.png)

**Comment by matrix3d** [comment]
先用旧的sdk https://www.dropbox.com/s/13mrzk4asw1qcq2/flexjs7.zip?dl=0
新版本sdk有bug，我正在和他们交流让他们修复

**Comment by matrix3d** [comment]
或者你把那几行错误代码加上 as Object

**Comment by matrix3d** [comment]
虽然是sdk的bug，但是我在代码这里给修了，更新代码吧

**Comment by elseswitch** [comment]
可以了，多谢

**Comment by matrix3d** [comment]
![default](https://cloud.githubusercontent.com/assets/4150631/18773892/1076c47e-8186-11e6-9a70-077426063757.gif)
